/**
 * PDF export using jsPDF + autoTable.
 */

import { ymd, parseLocalDate, forEachDay } from '../utils/dates.js';
import { isUsingTieredRates, validateTierInputs, computeTieredDailyCostsMap, getAdditionalCharges } from '../billing.js';
import { showButtonLoading, resetButtonLoading, scrollToAndHighlight } from '../ui.js';

export function exportToPDF() {
  const startDateInput = document.getElementById('startDate');
  const endDateInput = document.getElementById('endDate');
  const costPerKwhInput = document.getElementById('costPerKwh');
  const costPerKwhBox = costPerKwhInput.closest('.billing-box');
  const exportBtn = document.querySelector('[data-action="export-pdf"]');
  const startDateStr = startDateInput.value;
  const endDateStr = endDateInput.value;
  const costPerKwh = parseFloat(costPerKwhInput.value);
  const tiersOk = isUsingTieredRates() && validateTierInputs(true);

  let invalid = false;

  // Validate start date
  const startDate = parseLocalDate(startDateStr);
  if (!startDate) {
    alert('Please select a valid billing period start date.');
    startDateInput.classList.add('is-invalid');
    startDateInput.focus();
    startDateInput.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
    setTimeout(() => startDateInput.classList.remove('is-invalid'), 1500);
    invalid = true;
  } else {
    startDateInput.classList.remove('is-invalid');
  }

  // Validate end date
  const endDate = parseLocalDate(endDateStr);
  if (!endDate) {
    alert('Please select a valid billing period end date.');
    endDateInput.classList.add('is-invalid');
    endDateInput.focus();
    endDateInput.scrollIntoView({ behavior: 'smooth', block: 'center', inline: 'nearest' });
    setTimeout(() => endDateInput.classList.remove('is-invalid'), 1500);
    invalid = true;
  } else {
    endDateInput.classList.remove('is-invalid');
  }

  // Validate cost per kWh (only if not using tiers)
  if (!tiersOk && isNaN(costPerKwh)) {
    alert('Please enter a valid cost per kWh.');
    costPerKwhInput.classList.add('is-invalid');
    scrollToAndHighlight(costPerKwhBox);
    costPerKwhInput.focus();
    invalid = true;
  } else {
    costPerKwhInput.classList.remove('is-invalid');
  }

  if (invalid) return;

  showButtonLoading(exportBtn, 'Generating PDF...');

  setTimeout(() => {
    if (!startDate || !endDate || startDate > endDate) {
      alert('Please enter valid billing period dates.');
      resetButtonLoading(exportBtn, '<i class="bi bi-file-earmark-pdf-fill"></i> Export to PDF');
      return;
    }

    const data = [];
    const tierResult = computeTieredDailyCostsMap(isNaN(costPerKwh) ? 0 : costPerKwh, startDate, endDate);
    let totalKwh = tierResult.totalKwh;
    let totalCost = 0;

    forEachDay(startDate, endDate, (d) => {
      const dateStr = ymd(d);
      const kwh = tierResult.kwhMap[dateStr] || 0;
      const dailyCost = tierResult.dailyCostMap[dateStr] || 0;
      totalCost += dailyCost;
      const effectiveRateStr = kwh > 0 ? `$${(dailyCost / kwh).toFixed(3)}` : '';
      data.push([dateStr, kwh, effectiveRateStr, `$${dailyCost.toFixed(2)}`]);
    });

    // Additional charges
    const charges = getAdditionalCharges();
    if (charges.length > 0) {
      data.push(['Subtotal (kWh Usage)', totalKwh, '', `$${totalCost.toFixed(2)}`]);
      for (const charge of charges) {
        totalCost += charge.amount;
        data.push([charge.name, '', '', `$${charge.amount.toFixed(2)}`]);
      }
    }

    data.push(['TOTAL', totalKwh, '', `$${totalCost.toFixed(2)}`]);

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    doc.text('EV kWh Reimbursement Report', 14, 14);
    doc.setFontSize(10);
    doc.text(`Billing Period: ${startDateStr} to ${endDateStr}`, 14, 22);

    const usingTiers = isUsingTieredRates();
    const headerRate = usingTiers ? 'Tiered Rates' : `$${costPerKwh.toFixed(2)}`;
    doc.text(`Cost per kWh: ${headerRate}`, 14, 28);

    doc.autoTable({
      head: [['Date', 'kWh Usage', 'Cost per kWh', 'Daily Cost']],
      body: data,
      startY: 34,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] },
      footStyles: { fillColor: [41, 128, 185] },
      styles: { cellPadding: 2, fontSize: 10 },
      didDrawPage: function (data) {
        doc.setFontSize(8);
        doc.text('Generated by EV kWh Reimbursement App', 14, doc.internal.pageSize.height - 10);
      }
    });

    doc.save(`ev_reimbursement_${startDateStr}_to_${endDateStr}.pdf`);

    resetButtonLoading(exportBtn, '<i class="bi bi-file-earmark-pdf-fill"></i> Export to PDF');
  }, 400);
}
